### ISSUE TITLE
[NiceToHave] Create a simplified version of the simulation

### ISSUE THREAD

**Issue by ipa-nhg** [rosin-project/metacontrol_sim#4]
I tested the simulation and it works, great job @marioney :tada::tada:
The only problem I have is that the real time rate of gazebo is super slow (obviously the problem is my laptop, I usually use my workstation but these days I don't have access to it). Is it ok for you if I create a simplified version of the simulation? Probably just remove the controllers of the yumi will be ok.

----
Short test protocol:

**Installation**: https://github.com/rosin-project/metacontrol_sim/blob/1adaafb28d5a92acca70e175955c35e1204418f3/README.md#setup-using-wstool

**Command**: roslaunch metacontrol_sim ridgeback_yumi_world.launch **gui:=true**

**Test**:
Terminal A:
```
rostopic pub /ridgeback_velocity_controller/cmd_vel geometry_msgs/Twist "linear:
  x: 0.0
  y: 0.0
  z: 0.0
angular:
  x: 0.0
  y: 0.0
  z: 1.0" -r 10
```

Terminal B:
` rostopic echo /ridgeback_velocity_controller/odom`

The robot didn't move on gazebo but probably it is related to my computer...
